# Generated by Django 5.1.2 on 2025-02-16 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.CharField(max_length=255)),
                ('environment', models.CharField(max_length=50)),
                ('context', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='events_even_created_fd9f86_idx')],
            },
        ),
    ]
